### ISSUE TITLE
Fails to parse CSV header with quotes

### ISSUE THREAD

**Issue by Joaqim** [gregoranders/ts-csv#207]
Hi, I'm using ts-csv to process a CSV file where each entry is inside quotes, e.g:
```csv
"automatic_payout_id","automatic_payout_effective_at"....
"<id>","<date>",...
```
I get the error 'Invalid CSV at line 0:20' unless I unquote the first entry of the header like so: 
```javascript 
parser.parse(fileContent.replace(/^"automatic_payout_id"/, "automatic_payout_id"));
```

**To Reproduce**
```typescript
import Parser from '@gregoranders/csv';

// Works correctly:
//const fileContent = 'ROW1,ROW2\n"1","2"'
//const fileContent = 'ROW1,"ROW2"\n"1","2"'

// Doesn't work:
//const fileContent = '"ROW1",ROW2\n"1","2"'
const fileContent = '"ROW1","ROW2"\n"1","2"'
  
const result = parser.parse(fileContent);
// Error: Invalid CSV at 0:5
```
```log
at new ParseError (/home/jq/projects/ts-csv-sample/node_modules/@gregoranders/csv/src/index.ts:101:5)
    at Parser.handleQuoteNotEscaped (/home/jq/projects/ts-csv-sample/node_modules/@gregoranders/csv/src/index.ts:253:13)
    at Parser.handleQuote (/home/jq/projects/ts-csv-sample/node_modules/@gregoranders/csv/src/index.ts:236:14)
    at Parser.handleNext (/home/jq/projects/ts-csv-sample/node_modules/@gregoranders/csv/src/index.ts:226:10)
    at Parser.parse (/home/jq/projects/ts-csv-sample/node_modules/@gregoranders/csv/src/index.ts:163:12)
    at /home/jq/projects/ts-csv-sample/index.ts:20:25
    at Object.<anonymous> (/home/jq/projects/ts-csv-sample/index.ts:23:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/jq/projects/ts-csv-sample/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
```

**Expected behavior**
I assume that the CSV is valid since it parses correctly as long as the _first_ entry in header remains un-quoted.

**Desktop:**

- OS: Arch Linux
- Browser: Brave 1.24, Chromium 90
- Javascript V8 9.0

**Comment by gregoranders** [comment]
Sorry for the late answer. Quotes in CSV usually indicate the the value contains some character that needs to be quoted like a new line for example. You should be able to parse your example using a different quote character:

```ts
const parser = new TestSubject.Parser({quote: "'"});
```
